/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo_sync.v:1.1-45.10" *)
module fifo_sync(clk, cs, rst_n, wr_en, rd_en, data_in, data_out, empty, full);
  (* src = "fifo_sync.v:5.15-5.18" *)
  input clk;
  wire clk;
  (* src = "fifo_sync.v:6.15-6.17" *)
  input cs;
  wire cs;
  (* src = "fifo_sync.v:7.15-7.20" *)
  input rst_n;
  wire rst_n;
  (* src = "fifo_sync.v:8.15-8.20" *)
  input wr_en;
  wire wr_en;
  (* src = "fifo_sync.v:9.15-9.20" *)
  input rd_en;
  wire rd_en;
  (* src = "fifo_sync.v:10.32-10.39" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "fifo_sync.v:11.37-11.45" *)
  output [31:0] data_out;
  reg [31:0] data_out;
  (* src = "fifo_sync.v:12.16-12.21" *)
  output empty;
  wire empty;
  (* src = "fifo_sync.v:13.16-13.20" *)
  output full;
  wire full;
  (* src = "fifo_sync.v:30.5-42.7" *)
  wire [31:0] _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire [1:0] _0022_;
  wire [1:0] _0023_;
  wire [3:0] _0024_;
  wire [1:0] _0025_;
  wire _0026_;
  wire [3:0] _0027_;
  wire [1:0] _0028_;
  wire _0029_;
  wire [3:0] _0030_;
  wire [1:0] _0031_;
  wire _0032_;
  wire [3:0] _0033_;
  wire [1:0] _0034_;
  wire _0035_;
  wire [3:0] _0036_;
  wire [1:0] _0037_;
  wire _0038_;
  wire [3:0] _0039_;
  wire [1:0] _0040_;
  wire _0041_;
  wire [3:0] _0042_;
  wire [1:0] _0043_;
  wire _0044_;
  wire [3:0] _0045_;
  wire [1:0] _0046_;
  wire _0047_;
  wire [3:0] _0048_;
  wire [1:0] _0049_;
  wire _0050_;
  wire [3:0] _0051_;
  wire [1:0] _0052_;
  wire _0053_;
  wire [3:0] _0054_;
  wire [1:0] _0055_;
  wire _0056_;
  wire [3:0] _0057_;
  wire [1:0] _0058_;
  wire _0059_;
  wire [3:0] _0060_;
  wire [1:0] _0061_;
  wire _0062_;
  wire [3:0] _0063_;
  wire [1:0] _0064_;
  wire _0065_;
  wire [3:0] _0066_;
  wire [1:0] _0067_;
  wire _0068_;
  wire [3:0] _0069_;
  wire [1:0] _0070_;
  wire _0071_;
  wire [3:0] _0072_;
  wire [1:0] _0073_;
  wire _0074_;
  wire [3:0] _0075_;
  wire [1:0] _0076_;
  wire _0077_;
  wire [3:0] _0078_;
  wire [1:0] _0079_;
  wire _0080_;
  wire [3:0] _0081_;
  wire [1:0] _0082_;
  wire _0083_;
  wire [3:0] _0084_;
  wire [1:0] _0085_;
  wire _0086_;
  wire [3:0] _0087_;
  wire [1:0] _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire [3:0] _0092_;
  wire [1:0] _0093_;
  wire _0094_;
  wire [3:0] _0095_;
  wire [1:0] _0096_;
  wire _0097_;
  wire [3:0] _0098_;
  wire [1:0] _0099_;
  wire _0100_;
  wire [3:0] _0101_;
  wire [1:0] _0102_;
  wire _0103_;
  wire [3:0] _0104_;
  wire [1:0] _0105_;
  wire _0106_;
  wire [3:0] _0107_;
  wire [1:0] _0108_;
  wire _0109_;
  wire [3:0] _0110_;
  wire [1:0] _0111_;
  wire _0112_;
  wire [3:0] _0113_;
  wire [1:0] _0114_;
  wire _0115_;
  wire [3:0] _0116_;
  wire [1:0] _0117_;
  wire _0118_;
  wire [3:0] _0119_;
  wire [1:0] _0120_;
  wire _0121_;
  wire [3:0] _0122_;
  wire [1:0] _0123_;
  wire _0124_;
  wire [3:0] _0125_;
  wire [3:0] _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  (* src = "fifo_sync.v:24.41-24.56" *)
  wire _0399_;
  (* src = "fifo_sync.v:24.15-24.58" *)
  wire _0400_;
  (* src = "fifo_sync.v:24.15-24.26" *)
  wire _0401_;
  (* src = "fifo_sync.v:37.16-37.27" *)
  wire _0402_;
  (* src = "fifo_sync.v:37.16-37.37" *)
  wire _0403_;
  (* src = "fifo_sync.v:24.31-24.57" *)
  wire _0404_;
  (* src = "fifo_sync.v:44.37-44.61" *)
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _0422_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _0423_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _0424_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _0425_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _0426_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _0427_;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[0] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[1] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[2] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[3] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[4] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[5] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[6] ;
  (* src = "fifo_sync.v:15.25-15.29" *)
  reg [31:0] \fifo[7] ;
  (* src = "fifo_sync.v:17.22-17.34" *)
  reg [3:0] read_pointer;
  (* src = "fifo_sync.v:16.22-16.35" *)
  reg [3:0] write_pointer;
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) write_pointer[0] <= 1'h0;
    else if (_0400_) write_pointer[0] <= _0423_[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) write_pointer[1] <= 1'h0;
    else if (_0400_) write_pointer[1] <= _0424_[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) write_pointer[2] <= 1'h0;
    else if (_0400_) write_pointer[2] <= _0424_[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) write_pointer[3] <= 1'h0;
    else if (_0400_) write_pointer[3] <= _0424_[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0008_) \fifo[6] [31] <= data_in[31];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0007_) \fifo[7] [31] <= data_in[31];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0006_) \fifo[2] [31] <= data_in[31];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) read_pointer[0] <= 1'h0;
    else if (_0403_) read_pointer[0] <= _0426_[0];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) read_pointer[1] <= 1'h0;
    else if (_0403_) read_pointer[1] <= _0427_[1];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) read_pointer[2] <= 1'h0;
    else if (_0403_) read_pointer[2] <= _0427_[2];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) read_pointer[3] <= 1'h0;
    else if (_0403_) read_pointer[3] <= _0427_[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0005_) \fifo[4] [31] <= data_in[31];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[0] <= 1'h0;
    else if (_0403_) data_out[0] <= _0000_[0];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[1] <= 1'h0;
    else if (_0403_) data_out[1] <= _0000_[1];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[2] <= 1'h0;
    else if (_0403_) data_out[2] <= _0000_[2];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[3] <= 1'h0;
    else if (_0403_) data_out[3] <= _0000_[3];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[4] <= 1'h0;
    else if (_0403_) data_out[4] <= _0000_[4];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[5] <= 1'h0;
    else if (_0403_) data_out[5] <= _0000_[5];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[6] <= 1'h0;
    else if (_0403_) data_out[6] <= _0000_[6];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[7] <= 1'h0;
    else if (_0403_) data_out[7] <= _0000_[7];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[8] <= 1'h0;
    else if (_0403_) data_out[8] <= _0000_[8];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[9] <= 1'h0;
    else if (_0403_) data_out[9] <= _0000_[9];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[10] <= 1'h0;
    else if (_0403_) data_out[10] <= _0000_[10];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[11] <= 1'h0;
    else if (_0403_) data_out[11] <= _0000_[11];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[12] <= 1'h0;
    else if (_0403_) data_out[12] <= _0000_[12];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[13] <= 1'h0;
    else if (_0403_) data_out[13] <= _0000_[13];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[14] <= 1'h0;
    else if (_0403_) data_out[14] <= _0000_[14];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[15] <= 1'h0;
    else if (_0403_) data_out[15] <= _0000_[15];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[16] <= 1'h0;
    else if (_0403_) data_out[16] <= _0000_[16];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[17] <= 1'h0;
    else if (_0403_) data_out[17] <= _0000_[17];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[18] <= 1'h0;
    else if (_0403_) data_out[18] <= _0000_[18];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[19] <= 1'h0;
    else if (_0403_) data_out[19] <= _0000_[19];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[20] <= 1'h0;
    else if (_0403_) data_out[20] <= _0000_[20];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[21] <= 1'h0;
    else if (_0403_) data_out[21] <= _0000_[21];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[22] <= 1'h0;
    else if (_0403_) data_out[22] <= _0000_[22];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[23] <= 1'h0;
    else if (_0403_) data_out[23] <= _0000_[23];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[24] <= 1'h0;
    else if (_0403_) data_out[24] <= _0000_[24];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[25] <= 1'h0;
    else if (_0403_) data_out[25] <= _0000_[25];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[26] <= 1'h0;
    else if (_0403_) data_out[26] <= _0000_[26];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[27] <= 1'h0;
    else if (_0403_) data_out[27] <= _0000_[27];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[28] <= 1'h0;
    else if (_0403_) data_out[28] <= _0000_[28];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[29] <= 1'h0;
    else if (_0403_) data_out[29] <= _0000_[29];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[30] <= 1'h0;
    else if (_0403_) data_out[30] <= _0000_[30];
  (* src = "fifo_sync.v:30.5-42.7" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out[31] <= 1'h0;
    else if (_0403_) data_out[31] <= _0000_[31];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0004_) \fifo[5] [31] <= data_in[31];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0003_) \fifo[1] [31] <= data_in[31];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0002_) \fifo[0] [31] <= data_in[31];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [0] <= data_in[0];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [1] <= data_in[1];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [2] <= data_in[2];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [3] <= data_in[3];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [4] <= data_in[4];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [5] <= data_in[5];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [6] <= data_in[6];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [7] <= data_in[7];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [8] <= data_in[8];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [9] <= data_in[9];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [10] <= data_in[10];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [11] <= data_in[11];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [12] <= data_in[12];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [13] <= data_in[13];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [14] <= data_in[14];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [15] <= data_in[15];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [16] <= data_in[16];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [17] <= data_in[17];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [18] <= data_in[18];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [19] <= data_in[19];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [20] <= data_in[20];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [21] <= data_in[21];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [22] <= data_in[22];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [23] <= data_in[23];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [24] <= data_in[24];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [25] <= data_in[25];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [26] <= data_in[26];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [27] <= data_in[27];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [28] <= data_in[28];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [29] <= data_in[29];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [30] <= data_in[30];
  (* src = "fifo_sync.v:18.4-29.8" *)
  always @(posedge clk)
    if (_0001_) \fifo[3] [31] <= data_in[31];
  assign _0423_[0] = ~write_pointer[0];
  assign _0009_ = ~write_pointer[1];
  assign _0011_ = ~read_pointer[1];
  assign _0424_[1] = write_pointer[1] ^(* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  write_pointer[0];
  assign _0424_[2] = write_pointer[2] ^(* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0422_[1];
  assign _0424_[3] = write_pointer[3] ^(* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0422_[2];
  assign _0427_[1] = read_pointer[1] ^(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  read_pointer[0];
  assign _0427_[2] = read_pointer[2] ^(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0425_[1];
  assign _0427_[3] = read_pointer[3] ^(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0425_[2];
  assign _0422_[2] = write_pointer[2] &(* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0422_[1];
  assign _0422_[1] = write_pointer[1] &(* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  write_pointer[0];
  assign _0425_[2] = read_pointer[2] &(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0425_[1];
  assign _0425_[1] = read_pointer[1] &(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  read_pointer[0];
  assign _0125_[3] = read_pointer[3] ^(* src = "fifo_sync.v:43.20-43.49" *)  write_pointer[3];
  assign _0125_[0] = write_pointer[0] ^(* src = "fifo_sync.v:44.19-44.91" *)  read_pointer[0];
  assign _0125_[1] = write_pointer[1] ^(* src = "fifo_sync.v:44.19-44.91" *)  read_pointer[1];
  assign _0125_[2] = write_pointer[2] ^(* src = "fifo_sync.v:44.19-44.91" *)  read_pointer[2];
  assign _0126_[3] = write_pointer[3] ^(* src = "fifo_sync.v:44.19-44.91" *)  _0405_;
  assign _0127_ = _0013_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0012_;
  assign _0128_ = _0014_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0012_;
  assign _0129_ = _0015_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0012_;
  assign _0016_ = _0426_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0011_;
  assign _0130_ = _0016_ |(* src = "fifo_sync.v:39.25-39.29" *)  read_pointer[2];
  assign _0013_ = read_pointer[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0011_;
  assign _0131_ = _0013_ |(* src = "fifo_sync.v:39.25-39.29" *)  read_pointer[2];
  assign _0014_ = _0426_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  read_pointer[1];
  assign _0132_ = _0014_ |(* src = "fifo_sync.v:39.25-39.29" *)  read_pointer[2];
  assign _0133_ = _0017_ |(* src = "fifo_sync.v:26.13-26.58" *)  _0010_;
  assign _0018_ = write_pointer[0] |(* src = "fifo_sync.v:26.13-26.58" *)  _0009_;
  assign _0134_ = _0018_ |(* src = "fifo_sync.v:26.13-26.58" *)  _0010_;
  assign _0135_ = _0019_ |(* src = "fifo_sync.v:26.13-26.58" *)  _0010_;
  assign _0136_ = _0020_ |(* src = "fifo_sync.v:26.13-26.58" *)  _0010_;
  assign _0017_ = _0423_[0] |(* src = "fifo_sync.v:26.13-26.58" *)  _0009_;
  assign _0137_ = _0017_ |(* src = "fifo_sync.v:26.13-26.58" *)  write_pointer[2];
  assign _0138_ = _0018_ |(* src = "fifo_sync.v:26.13-26.58" *)  write_pointer[2];
  assign _0019_ = _0423_[0] |(* src = "fifo_sync.v:26.13-26.58" *)  write_pointer[1];
  assign _0139_ = _0019_ |(* src = "fifo_sync.v:26.13-26.58" *)  write_pointer[2];
  assign _0008_ = _0021_ & _0418_;
  assign _0007_ = _0021_ & _0417_;
  assign _0006_ = _0021_ & _0406_;
  assign _0005_ = _0021_ & _0420_;
  assign _0004_ = _0021_ & _0419_;
  assign _0003_ = _0021_ & _0407_;
  assign _0002_ = _0021_ & _0408_;
  assign _0021_ = rst_n & _0400_;
  assign _0001_ = _0021_ & _0421_;
  assign _0022_[1] = _0125_[2] |(* src = "fifo_sync.v:43.20-43.49" *)  _0125_[3];
  assign _0140_ = _0022_[0] |(* src = "fifo_sync.v:43.20-43.49" *)  _0022_[1];
  assign _0022_[0] = _0125_[0] |(* src = "fifo_sync.v:44.19-44.91" *)  _0125_[1];
  assign _0023_[1] = _0125_[2] |(* src = "fifo_sync.v:44.19-44.91" *)  _0126_[3];
  assign _0141_ = _0022_[0] |(* src = "fifo_sync.v:44.19-44.91" *)  _0023_[1];
  assign _0142_ = _0016_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0012_;
  assign _0024_[0] = _0393_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0394_;
  assign _0024_[1] = _0395_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0396_;
  assign _0024_[2] = _0397_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0398_;
  assign _0024_[3] = _0143_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0144_;
  assign _0025_[0] = _0024_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0024_[1];
  assign _0025_[1] = _0024_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0024_[3];
  assign _0026_ = _0025_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0025_[1];
  assign _0027_[0] = _0145_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0146_;
  assign _0027_[1] = _0147_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0148_;
  assign _0027_[2] = _0149_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0150_;
  assign _0027_[3] = _0151_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0152_;
  assign _0028_[0] = _0027_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0027_[1];
  assign _0028_[1] = _0027_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0027_[3];
  assign _0029_ = _0028_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0028_[1];
  assign _0030_[0] = _0153_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0154_;
  assign _0030_[1] = _0155_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0156_;
  assign _0030_[2] = _0157_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0158_;
  assign _0030_[3] = _0159_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0160_;
  assign _0031_[0] = _0030_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0030_[1];
  assign _0031_[1] = _0030_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0030_[3];
  assign _0032_ = _0031_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0031_[1];
  assign _0033_[0] = _0161_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0162_;
  assign _0033_[1] = _0163_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0164_;
  assign _0033_[2] = _0165_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0166_;
  assign _0033_[3] = _0167_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0168_;
  assign _0034_[0] = _0033_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0033_[1];
  assign _0034_[1] = _0033_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0033_[3];
  assign _0035_ = _0034_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0034_[1];
  assign _0036_[0] = _0169_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0170_;
  assign _0036_[1] = _0171_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0172_;
  assign _0036_[2] = _0173_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0174_;
  assign _0036_[3] = _0175_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0176_;
  assign _0037_[0] = _0036_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0036_[1];
  assign _0037_[1] = _0036_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0036_[3];
  assign _0038_ = _0037_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0037_[1];
  assign _0039_[0] = _0177_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0178_;
  assign _0039_[1] = _0179_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0180_;
  assign _0039_[2] = _0181_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0182_;
  assign _0039_[3] = _0183_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0184_;
  assign _0040_[0] = _0039_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0039_[1];
  assign _0040_[1] = _0039_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0039_[3];
  assign _0041_ = _0040_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0040_[1];
  assign _0042_[0] = _0185_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0186_;
  assign _0042_[1] = _0187_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0188_;
  assign _0042_[2] = _0189_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0190_;
  assign _0042_[3] = _0191_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0192_;
  assign _0043_[0] = _0042_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0042_[1];
  assign _0043_[1] = _0042_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0042_[3];
  assign _0044_ = _0043_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0043_[1];
  assign _0045_[0] = _0193_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0194_;
  assign _0045_[1] = _0195_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0196_;
  assign _0045_[2] = _0197_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0198_;
  assign _0045_[3] = _0199_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0200_;
  assign _0046_[0] = _0045_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0045_[1];
  assign _0046_[1] = _0045_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0045_[3];
  assign _0047_ = _0046_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0046_[1];
  assign _0048_[0] = _0201_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0202_;
  assign _0048_[1] = _0203_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0204_;
  assign _0048_[2] = _0205_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0206_;
  assign _0048_[3] = _0207_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0208_;
  assign _0049_[0] = _0048_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0048_[1];
  assign _0049_[1] = _0048_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0048_[3];
  assign _0050_ = _0049_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0049_[1];
  assign _0051_[0] = _0209_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0210_;
  assign _0051_[1] = _0211_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0212_;
  assign _0051_[2] = _0213_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0214_;
  assign _0051_[3] = _0215_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0216_;
  assign _0052_[0] = _0051_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0051_[1];
  assign _0052_[1] = _0051_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0051_[3];
  assign _0053_ = _0052_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0052_[1];
  assign _0054_[0] = _0217_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0218_;
  assign _0054_[1] = _0219_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0220_;
  assign _0054_[2] = _0221_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0222_;
  assign _0054_[3] = _0223_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0224_;
  assign _0055_[0] = _0054_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0054_[1];
  assign _0055_[1] = _0054_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0054_[3];
  assign _0056_ = _0055_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0055_[1];
  assign _0057_[0] = _0225_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0226_;
  assign _0057_[1] = _0227_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0228_;
  assign _0057_[2] = _0229_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0230_;
  assign _0057_[3] = _0231_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0232_;
  assign _0058_[0] = _0057_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0057_[1];
  assign _0058_[1] = _0057_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0057_[3];
  assign _0059_ = _0058_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0058_[1];
  assign _0060_[0] = _0233_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0234_;
  assign _0060_[1] = _0235_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0236_;
  assign _0060_[2] = _0237_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0238_;
  assign _0060_[3] = _0239_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0240_;
  assign _0061_[0] = _0060_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0060_[1];
  assign _0061_[1] = _0060_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0060_[3];
  assign _0062_ = _0061_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0061_[1];
  assign _0063_[0] = _0241_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0242_;
  assign _0063_[1] = _0243_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0244_;
  assign _0063_[2] = _0245_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0246_;
  assign _0063_[3] = _0247_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0248_;
  assign _0064_[0] = _0063_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0063_[1];
  assign _0064_[1] = _0063_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0063_[3];
  assign _0065_ = _0064_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0064_[1];
  assign _0066_[0] = _0249_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0250_;
  assign _0066_[1] = _0251_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0252_;
  assign _0066_[2] = _0253_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0254_;
  assign _0066_[3] = _0255_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0256_;
  assign _0067_[0] = _0066_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0066_[1];
  assign _0067_[1] = _0066_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0066_[3];
  assign _0068_ = _0067_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0067_[1];
  assign _0069_[0] = _0257_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0258_;
  assign _0069_[1] = _0259_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0260_;
  assign _0069_[2] = _0261_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0262_;
  assign _0069_[3] = _0263_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0264_;
  assign _0070_[0] = _0069_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0069_[1];
  assign _0070_[1] = _0069_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0069_[3];
  assign _0071_ = _0070_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0070_[1];
  assign _0072_[0] = _0265_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0266_;
  assign _0072_[1] = _0267_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0268_;
  assign _0072_[2] = _0269_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0270_;
  assign _0072_[3] = _0271_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0272_;
  assign _0073_[0] = _0072_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0072_[1];
  assign _0073_[1] = _0072_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0072_[3];
  assign _0074_ = _0073_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0073_[1];
  assign _0075_[0] = _0273_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0274_;
  assign _0075_[1] = _0275_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0276_;
  assign _0075_[2] = _0277_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0278_;
  assign _0075_[3] = _0279_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0280_;
  assign _0076_[0] = _0075_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0075_[1];
  assign _0076_[1] = _0075_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0075_[3];
  assign _0077_ = _0076_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0076_[1];
  assign _0078_[0] = _0281_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0282_;
  assign _0078_[1] = _0283_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0284_;
  assign _0078_[2] = _0285_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0286_;
  assign _0078_[3] = _0287_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0288_;
  assign _0079_[0] = _0078_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0078_[1];
  assign _0079_[1] = _0078_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0078_[3];
  assign _0080_ = _0079_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0079_[1];
  assign _0081_[0] = _0289_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0290_;
  assign _0081_[1] = _0291_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0292_;
  assign _0081_[2] = _0293_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0294_;
  assign _0081_[3] = _0295_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0296_;
  assign _0082_[0] = _0081_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0081_[1];
  assign _0082_[1] = _0081_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0081_[3];
  assign _0083_ = _0082_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0082_[1];
  assign _0084_[0] = _0297_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0298_;
  assign _0084_[1] = _0299_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0300_;
  assign _0084_[2] = _0301_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0302_;
  assign _0084_[3] = _0303_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0304_;
  assign _0085_[0] = _0084_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0084_[1];
  assign _0085_[1] = _0084_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0084_[3];
  assign _0086_ = _0085_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0085_[1];
  assign _0087_[0] = _0305_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0306_;
  assign _0087_[1] = _0307_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0308_;
  assign _0087_[2] = _0309_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0310_;
  assign _0087_[3] = _0311_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0312_;
  assign _0088_[0] = _0087_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0087_[1];
  assign _0088_[1] = _0087_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0087_[3];
  assign _0089_ = _0088_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0088_[1];
  assign _0015_ = read_pointer[0] |(* src = "fifo_sync.v:39.25-39.29" *)  read_pointer[1];
  assign _0090_ = _0015_ |(* src = "fifo_sync.v:39.25-39.29" *)  read_pointer[2];
  assign _0020_ = write_pointer[0] |(* src = "fifo_sync.v:26.13-26.58" *)  write_pointer[1];
  assign _0091_ = _0020_ |(* src = "fifo_sync.v:26.13-26.58" *)  write_pointer[2];
  assign _0092_[0] = _0409_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0092_[1] = _0411_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0092_[2] = _0413_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0092_[3] = _0415_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0093_[0] = _0092_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0092_[1];
  assign _0093_[1] = _0092_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0092_[3];
  assign _0094_ = _0093_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0093_[1];
  assign _0095_[0] = _0313_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0314_;
  assign _0095_[1] = _0315_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0316_;
  assign _0095_[2] = _0317_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0318_;
  assign _0095_[3] = _0319_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0320_;
  assign _0096_[0] = _0095_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0095_[1];
  assign _0096_[1] = _0095_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0095_[3];
  assign _0097_ = _0096_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0096_[1];
  assign _0098_[0] = _0321_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0322_;
  assign _0098_[1] = _0323_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0324_;
  assign _0098_[2] = _0325_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0326_;
  assign _0098_[3] = _0327_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0328_;
  assign _0099_[0] = _0098_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0098_[1];
  assign _0099_[1] = _0098_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0098_[3];
  assign _0100_ = _0099_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0099_[1];
  assign _0101_[0] = _0329_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0330_;
  assign _0101_[1] = _0331_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0332_;
  assign _0101_[2] = _0333_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0334_;
  assign _0101_[3] = _0335_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0336_;
  assign _0102_[0] = _0101_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0101_[1];
  assign _0102_[1] = _0101_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0101_[3];
  assign _0103_ = _0102_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0102_[1];
  assign _0104_[0] = _0337_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0338_;
  assign _0104_[1] = _0339_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0340_;
  assign _0104_[2] = _0341_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0342_;
  assign _0104_[3] = _0343_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0344_;
  assign _0105_[0] = _0104_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0104_[1];
  assign _0105_[1] = _0104_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0104_[3];
  assign _0106_ = _0105_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0105_[1];
  assign _0107_[0] = _0345_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0346_;
  assign _0107_[1] = _0347_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0348_;
  assign _0107_[2] = _0349_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0350_;
  assign _0107_[3] = _0351_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0352_;
  assign _0108_[0] = _0107_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0107_[1];
  assign _0108_[1] = _0107_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0107_[3];
  assign _0109_ = _0108_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0108_[1];
  assign _0110_[0] = _0353_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0354_;
  assign _0110_[1] = _0355_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0356_;
  assign _0110_[2] = _0357_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0358_;
  assign _0110_[3] = _0359_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0360_;
  assign _0111_[0] = _0110_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0110_[1];
  assign _0111_[1] = _0110_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0110_[3];
  assign _0112_ = _0111_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0111_[1];
  assign _0113_[0] = _0361_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0362_;
  assign _0113_[1] = _0363_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0364_;
  assign _0113_[2] = _0365_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0366_;
  assign _0113_[3] = _0367_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0368_;
  assign _0114_[0] = _0113_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0113_[1];
  assign _0114_[1] = _0113_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0113_[3];
  assign _0115_ = _0114_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0114_[1];
  assign _0116_[0] = _0369_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0370_;
  assign _0116_[1] = _0371_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0372_;
  assign _0116_[2] = _0373_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0374_;
  assign _0116_[3] = _0375_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0376_;
  assign _0117_[0] = _0116_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0116_[1];
  assign _0117_[1] = _0116_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0116_[3];
  assign _0118_ = _0117_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0117_[1];
  assign _0119_[0] = _0377_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0378_;
  assign _0119_[1] = _0379_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0380_;
  assign _0119_[2] = _0381_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0382_;
  assign _0119_[3] = _0383_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0384_;
  assign _0120_[0] = _0119_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0119_[1];
  assign _0120_[1] = _0119_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0119_[3];
  assign _0121_ = _0120_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0120_[1];
  assign _0122_[0] = _0385_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0386_;
  assign _0122_[1] = _0387_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0388_;
  assign _0122_[2] = _0389_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0390_;
  assign _0122_[3] = _0391_ |(* src = "fifo_sync.v:39.25-39.29" *)  _0392_;
  assign _0123_[0] = _0122_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0122_[1];
  assign _0123_[1] = _0122_[2] |(* src = "fifo_sync.v:39.25-39.29" *)  _0122_[3];
  assign _0124_ = _0123_[0] |(* src = "fifo_sync.v:39.25-39.29" *)  _0123_[1];
  assign _0410_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0127_;
  assign _0411_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0128_;
  assign _0412_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0129_;
  assign _0413_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0130_;
  assign _0414_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0131_;
  assign _0415_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0132_;
  assign _0416_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0090_;
  assign _0417_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0133_;
  assign _0418_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0134_;
  assign _0419_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0135_;
  assign _0420_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0136_;
  assign _0421_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0137_;
  assign _0406_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0138_;
  assign _0407_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0139_;
  assign _0408_ = ~(* src = "fifo_sync.v:26.13-26.58" *) _0091_;
  assign empty = ~(* src = "fifo_sync.v:43.20-43.49" *) _0140_;
  assign full = ~(* src = "fifo_sync.v:44.19-44.91" *) _0141_;
  assign _0409_ = ~(* src = "fifo_sync.v:39.25-39.29" *) _0142_;
  assign _0401_ = cs &(* src = "fifo_sync.v:24.15-24.26" *)  wr_en;
  assign _0399_ = rd_en &(* src = "fifo_sync.v:24.41-24.56" *)  _0140_;
  assign _0404_ = _0141_ |(* src = "fifo_sync.v:24.31-24.57" *)  _0399_;
  assign _0400_ = _0401_ &(* src = "fifo_sync.v:24.15-24.58" *)  _0404_;
  assign _0402_ = cs &(* src = "fifo_sync.v:37.16-37.27" *)  rd_en;
  assign _0403_ = _0402_ &(* src = "fifo_sync.v:37.16-37.37" *)  _0140_;
  assign _0144_ = \fifo[0] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0145_ = \fifo[7] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0146_ = \fifo[6] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0147_ = \fifo[5] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0148_ = \fifo[4] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0149_ = \fifo[3] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0150_ = \fifo[2] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0151_ = \fifo[1] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0152_ = \fifo[0] [11] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0153_ = \fifo[7] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0154_ = \fifo[6] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0155_ = \fifo[5] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0156_ = \fifo[4] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0157_ = \fifo[3] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0158_ = \fifo[2] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0159_ = \fifo[1] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0160_ = \fifo[0] [12] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0161_ = \fifo[7] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0162_ = \fifo[6] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0163_ = \fifo[5] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0164_ = \fifo[4] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0165_ = \fifo[3] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0166_ = \fifo[2] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0167_ = \fifo[1] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0168_ = \fifo[0] [13] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0169_ = \fifo[7] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0170_ = \fifo[6] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0171_ = \fifo[5] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0172_ = \fifo[4] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0173_ = \fifo[3] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0174_ = \fifo[2] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0175_ = \fifo[1] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0176_ = \fifo[0] [14] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0177_ = \fifo[7] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0178_ = \fifo[6] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0179_ = \fifo[5] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0180_ = \fifo[4] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0181_ = \fifo[3] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0182_ = \fifo[2] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0183_ = \fifo[1] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0184_ = \fifo[0] [15] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0185_ = \fifo[7] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0186_ = \fifo[6] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0187_ = \fifo[5] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0188_ = \fifo[4] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0189_ = \fifo[3] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0190_ = \fifo[2] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0191_ = \fifo[1] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0192_ = \fifo[0] [16] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0193_ = \fifo[7] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0194_ = \fifo[6] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0195_ = \fifo[5] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0196_ = \fifo[4] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0197_ = \fifo[3] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0198_ = \fifo[2] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0199_ = \fifo[1] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0200_ = \fifo[0] [17] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0201_ = \fifo[7] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0202_ = \fifo[6] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0203_ = \fifo[5] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0204_ = \fifo[4] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0205_ = \fifo[3] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0206_ = \fifo[2] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0207_ = \fifo[1] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0208_ = \fifo[0] [18] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0209_ = \fifo[7] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0210_ = \fifo[6] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0211_ = \fifo[5] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0212_ = \fifo[4] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0213_ = \fifo[3] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0214_ = \fifo[2] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0215_ = \fifo[1] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0216_ = \fifo[0] [19] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0217_ = \fifo[7] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0218_ = \fifo[6] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0219_ = \fifo[5] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0220_ = \fifo[4] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0221_ = \fifo[3] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0222_ = \fifo[2] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0223_ = \fifo[1] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0224_ = \fifo[0] [20] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0225_ = \fifo[7] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0226_ = \fifo[6] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0227_ = \fifo[5] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0228_ = \fifo[4] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0229_ = \fifo[3] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0230_ = \fifo[2] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0231_ = \fifo[1] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0232_ = \fifo[0] [21] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0233_ = \fifo[7] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0234_ = \fifo[6] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0235_ = \fifo[5] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0236_ = \fifo[4] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0237_ = \fifo[3] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0238_ = \fifo[2] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0239_ = \fifo[1] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0240_ = \fifo[0] [22] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0241_ = \fifo[7] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0242_ = \fifo[6] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0243_ = \fifo[5] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0244_ = \fifo[4] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0245_ = \fifo[3] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0246_ = \fifo[2] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0247_ = \fifo[1] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0248_ = \fifo[0] [23] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0249_ = \fifo[7] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0250_ = \fifo[6] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0251_ = \fifo[5] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0252_ = \fifo[4] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0253_ = \fifo[3] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0254_ = \fifo[2] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0255_ = \fifo[1] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0256_ = \fifo[0] [24] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0257_ = \fifo[7] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0258_ = \fifo[6] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0259_ = \fifo[5] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0260_ = \fifo[4] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0261_ = \fifo[3] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0262_ = \fifo[2] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0263_ = \fifo[1] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0264_ = \fifo[0] [25] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0265_ = \fifo[7] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0266_ = \fifo[6] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0267_ = \fifo[5] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0268_ = \fifo[4] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0269_ = \fifo[3] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0270_ = \fifo[2] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0271_ = \fifo[1] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0272_ = \fifo[0] [26] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0273_ = \fifo[7] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0274_ = \fifo[6] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0275_ = \fifo[5] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0276_ = \fifo[4] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0277_ = \fifo[3] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0278_ = \fifo[2] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0279_ = \fifo[1] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0280_ = \fifo[0] [27] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0281_ = \fifo[7] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0282_ = \fifo[6] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0283_ = \fifo[5] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0284_ = \fifo[4] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0285_ = \fifo[3] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0286_ = \fifo[2] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0287_ = \fifo[1] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0288_ = \fifo[0] [28] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0289_ = \fifo[7] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0290_ = \fifo[6] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0291_ = \fifo[5] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0292_ = \fifo[4] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0293_ = \fifo[3] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0294_ = \fifo[2] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0295_ = \fifo[1] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0296_ = \fifo[0] [29] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0297_ = \fifo[7] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0298_ = \fifo[6] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0299_ = \fifo[5] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0300_ = \fifo[4] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0301_ = \fifo[3] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0302_ = \fifo[2] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0303_ = \fifo[1] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0304_ = \fifo[0] [30] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0305_ = \fifo[7] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0306_ = \fifo[6] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0307_ = \fifo[5] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0308_ = \fifo[4] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0309_ = \fifo[3] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0310_ = \fifo[2] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0311_ = \fifo[1] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0312_ = \fifo[0] [31] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0313_ = \fifo[7] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0314_ = \fifo[6] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0315_ = \fifo[5] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0316_ = \fifo[4] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0317_ = \fifo[3] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0318_ = \fifo[2] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0319_ = \fifo[1] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0320_ = \fifo[0] [0] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0321_ = \fifo[7] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0322_ = \fifo[6] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0323_ = \fifo[5] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0324_ = \fifo[4] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0325_ = \fifo[3] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0326_ = \fifo[2] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0327_ = \fifo[1] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0328_ = \fifo[0] [1] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0329_ = \fifo[7] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0330_ = \fifo[6] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0331_ = \fifo[5] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0332_ = \fifo[4] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0333_ = \fifo[3] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0334_ = \fifo[2] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0335_ = \fifo[1] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0336_ = \fifo[0] [2] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0337_ = \fifo[7] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0338_ = \fifo[6] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0339_ = \fifo[5] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0340_ = \fifo[4] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0341_ = \fifo[3] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0342_ = \fifo[2] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0343_ = \fifo[1] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0344_ = \fifo[0] [3] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0345_ = \fifo[7] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0346_ = \fifo[6] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0347_ = \fifo[5] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0348_ = \fifo[4] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0349_ = \fifo[3] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0350_ = \fifo[2] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0351_ = \fifo[1] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0352_ = \fifo[0] [4] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0353_ = \fifo[7] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0354_ = \fifo[6] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0355_ = \fifo[5] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0356_ = \fifo[4] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0357_ = \fifo[3] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0358_ = \fifo[2] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0359_ = \fifo[1] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0360_ = \fifo[0] [5] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0361_ = \fifo[7] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0362_ = \fifo[6] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0363_ = \fifo[5] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0364_ = \fifo[4] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0365_ = \fifo[3] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0366_ = \fifo[2] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0367_ = \fifo[1] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0368_ = \fifo[0] [6] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0369_ = \fifo[7] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0370_ = \fifo[6] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0371_ = \fifo[5] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0372_ = \fifo[4] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0373_ = \fifo[3] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0374_ = \fifo[2] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0375_ = \fifo[1] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0376_ = \fifo[0] [7] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0377_ = \fifo[7] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0378_ = \fifo[6] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0379_ = \fifo[5] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0380_ = \fifo[4] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0381_ = \fifo[3] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0382_ = \fifo[2] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0383_ = \fifo[1] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0384_ = \fifo[0] [8] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0385_ = \fifo[7] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0386_ = \fifo[6] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0387_ = \fifo[5] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0388_ = \fifo[4] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0389_ = \fifo[3] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0390_ = \fifo[2] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0391_ = \fifo[1] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0392_ = \fifo[0] [9] &(* src = "fifo_sync.v:39.25-39.29" *)  _0416_;
  assign _0393_ = \fifo[7] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0409_;
  assign _0394_ = \fifo[6] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0410_;
  assign _0395_ = \fifo[5] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0411_;
  assign _0396_ = \fifo[4] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0412_;
  assign _0397_ = \fifo[3] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0413_;
  assign _0398_ = \fifo[2] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0414_;
  assign _0143_ = \fifo[1] [10] &(* src = "fifo_sync.v:39.25-39.29" *)  _0415_;
  assign _0010_ = ~(* src = "fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) write_pointer[2];
  assign _0426_[0] = ~(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) read_pointer[0];
  assign _0012_ = ~(* src = "fifo_sync.v:40.29-40.48|fifo_sync.v:27.30-27.50|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) read_pointer[2];
  assign _0405_ = ~(* src = "fifo_sync.v:44.37-44.61" *) read_pointer[3];
  assign _0000_[10] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0026_ : 1'hx;
  assign _0000_[11] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0029_ : 1'hx;
  assign _0000_[12] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0032_ : 1'hx;
  assign _0000_[13] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0035_ : 1'hx;
  assign _0000_[14] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0038_ : 1'hx;
  assign _0000_[15] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0041_ : 1'hx;
  assign _0000_[16] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0044_ : 1'hx;
  assign _0000_[17] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0047_ : 1'hx;
  assign _0000_[18] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0050_ : 1'hx;
  assign _0000_[19] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0053_ : 1'hx;
  assign _0000_[20] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0056_ : 1'hx;
  assign _0000_[21] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0059_ : 1'hx;
  assign _0000_[22] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0062_ : 1'hx;
  assign _0000_[23] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0065_ : 1'hx;
  assign _0000_[24] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0068_ : 1'hx;
  assign _0000_[25] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0071_ : 1'hx;
  assign _0000_[26] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0074_ : 1'hx;
  assign _0000_[27] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0077_ : 1'hx;
  assign _0000_[28] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0080_ : 1'hx;
  assign _0000_[29] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0083_ : 1'hx;
  assign _0000_[30] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0086_ : 1'hx;
  assign _0000_[31] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0089_ : 1'hx;
  assign _0000_[0] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0097_ : 1'hx;
  assign _0000_[1] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0100_ : 1'hx;
  assign _0000_[2] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0103_ : 1'hx;
  assign _0000_[3] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0106_ : 1'hx;
  assign _0000_[4] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0109_ : 1'hx;
  assign _0000_[5] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0112_ : 1'hx;
  assign _0000_[6] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0115_ : 1'hx;
  assign _0000_[7] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0118_ : 1'hx;
  assign _0000_[8] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0121_ : 1'hx;
  assign _0000_[9] = _0094_ ? (* src = "fifo_sync.v:39.25-39.29" *) _0124_ : 1'hx;
  assign _0422_[0] = write_pointer[0];
  assign _0023_[0] = _0022_[0];
  assign _0126_[2:0] = _0125_[2:0];
  assign _0425_[0] = read_pointer[0];
  assign _0424_[0] = _0423_[0];
  assign _0426_[3:1] = read_pointer[3:1];
  assign _0427_[0] = _0426_[0];
  assign _0423_[3:1] = write_pointer[3:1];
endmodule
